CREATE TABLE if not exists "student" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL,
	"age"	INTEGER NOT NULL,
	"sex"	INTEGER NOT NULL,
	"ts"	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id" AUTOINCREMENT)
)
